### ISSUE TITLE
How can I generate SBOM for a docker image?

### ISSUE THREAD

**Issue by FeynmanZhou** [microsoft/sbom-tool#100]
I want to generate SBOM for a docker image, but the command line requires multiple parameters according to [this sample](https://github.com/microsoft/sbom-tool/blob/main/docs/sbom-tool-cli-reference.md#scan-docker-images-for-dependency-packages),  which looks complicated. Is there a simple way to generate SBOM for a docker image like [Docker Sbom](https://docs.docker.com/engine/sbom/)?

**Comment by bureado** [comment]
The easiest way I've found is `./sbom-tool generate -di <imageref> -b ./foo -pn bar -pv 0.1 -bc ./foo` where `foo` is an empty directory, and `pn=bar` is a namespace for the generated SBOM.

**Comment by aasim** [comment]
@bureado has the right answer, that is the way to generate SBOMs using our tool.

Although, baz is not a valid URI, we need a valid URI as a parameter for the -nsb parameter.
