### ISSUE TITLE
Add a default 6-minute timeout on CD

### ISSUE THREAD

**Issue by aasim** [microsoft/sbom-tool#105]
Add a timeout while calling the CD code so that we don't spend more than 6 minutes running their code and to prevent any hangs.

**Comment by JamieMagee** [comment]
We discussed this on our side, and we should be using the standard `CancellationToken` pattern[^1] if possible. From your side you will create a `CancellationTokenSource`, add a timeout, and provide us with the `CancellationToken`

```C#
var cts = new CancellationTokenSource();
cts.CancelAfter(TimeSpan.FromMinutes(6));
componentDetectionOrchestrator(args, cts.Token);
```

[^1]: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/cancel-async-tasks-after-a-period-of-time

**Comment by ksigmund** [comment]
We ended up using a default of 15 minutes, which can be overridden by adding the `Timeout` argument, alone with the number of seconds, to the list of `AdditionalComponentDetectorArgs`.
