### ISSUE TITLE
Using private pypi repositories

### ISSUE THREAD

**Issue by mschmieder** [microsoft/sbom-tool#106]
Hello,

I'm currently trying to see how we can use the sbom tool for our different software development platforms that use .netcore as well as python heavily.

I was trying to use the tool with a python projects that pulls in modules from a private pypi repository. Unfortunately the tool does not seem to recognise neither the PIP_CONFIG_FILE nor the PIP_EXTRA_INDEX_URLS.

Is there a way to use private repositories as well? I did not find anything within the docs.

Thanks

**Comment by edgarrs** [comment]
@aasim to redirect issue with Component Detectors

**Comment by aasim** [comment]
@mschmieder Please refer to this document on how we parse out Python packages: https://github.com/microsoft/component-detection/blob/main/docs/detectors/pip.md.

If you have any further questions on how python detection works or if we can scan private repositories, please open an issue on the [component-detection](https://github.com/microsoft/component-detection/issues) repository, they will be able to help you out better. We use their tools under the hood and their answer will be our answer.

Closing out this issue.
