### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/sbom-tool#109]
Create a GitHub Action to install and/or run the SBOM tool.

This doesn't need to be overly complex, and I would look to examples like [sigstore/cosign-installer][1] which has achieved this with a Bash script (No TypeScript/JavaScript required!)

[1]: https://github.com/sigstore/cosign-installer

**Comment by Brend-Smits** [comment]
Hey @JamieMagee, 

We created a small [sbom-tool-installer-action](https://github.com/philips-software/sbom-tool-installer-action) that currently just installs the sbom-tool and adds it to the $PATH for later easy use.
When the maintainers decide to sign their releases #44, we will also check for this. Hopefully it helps!

**Comment by JamieMagee** [comment]
@Brend-Smits Wow! Thank you. I should have searched a little harder 😅 

I was mainly suggesting writing it in Bash instead of TypeScript to avoid the compilation step. But, if you've got a TypeScript version working, then no reason to change it.

**Comment by aasim** [comment]
Exciting @Brend-Smits! thanks that looks great.

@JamieMagee - we do have some docs on how to setup github actions for our tool [here](https://github.com/microsoft/sbom-tool/blob/main/docs/setting-up-github-actions.md), let me know if it needs any improvements.

**Comment by edgarrs** [comment]
Thank you @Brend-Smits for creating the GitHub Action
