### ISSUE TITLE
Encountered error while running ManifestTool generation workflow. 

### ISSUE THREAD

**Issue by newertp** [microsoft/sbom-tool#114]
ENV: Ubuntu-20.04
Encountered error while running ManifestTool generation workflow. Error: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMonoPosixHelper: cannot open shared object file: No such file or directory

The same environment, when I used sbom-tool v0.1.13 to scan source code, it can generate sbom file correctly. But, it encountered the error above when I use sbom-tool v0.2.0. How to fix it?  The command is as follows:
salus Generate -b ./test -bc ./test -di test:latest -pn Test -pv 0.0.1 -nsb https://test.com/ -V Verbose -m .

**Comment by newertp** [comment]
sorry, the command is below:
salus Generate -b ./test -bc ./test -pn Test -pv 0.0.1 -nsb https://test.com/ -V Verbose -m .

**Comment by johnbfs-dev** [comment]
Get this package installed to your Linux distribution
https://www.mono-project.com/download/stable/#download-lin

**Comment by aasim** [comment]
Hi @newertp - I just checked and looks like the newer version has some issues and I have rolled back the change. Please continue to use v0.1.13 for now, as we put out a fix to the new version, thanks.
