### ISSUE TITLE
'SPDX:2.2' is not supported by the SBOM tool

### ISSUE THREAD

**Issue by johnbfs-dev** [microsoft/sbom-tool#115]
Encountered error while running ManifestTool generation workflow. Error: The SBOM format 'SPDX:2.2' is not supported by the SBOM tool.

Same error for Ubuntu 22.04 LTS and Debian 11

**Comment by bruzzlerli** [comment]
Seeing the same on version v0.2.0 on Windows. The previous version v0.1.13 works as a temporary solution.

**Comment by gizmohd** [comment]
Seeing same error on Redhat/CentOS

**Comment by aasim** [comment]
I think the new version has some issues; I am rolling it back, please continue to use v0.1.13 for now.
