### ISSUE TITLE
Documentation error and SBOM format error

### ISSUE THREAD

**Issue by daneshbadlani** [microsoft/sbom-tool#117]
Mark Russinovich (Azure CTO) tried the tool and found a minor doc bug where “sbom-tool” is missing in this sample command line:

![image001](https://user-images.githubusercontent.com/38691121/186950052-fa7f79e4-f737-4182-89a8-1135542ad90e.png)

He also faced the following error when trying to run the guidance: 

![image002](https://user-images.githubusercontent.com/38691121/186950196-71effbac-2910-4fe8-b979-5ab7d94f0fab.png)

**Comment by adriandiglio** [comment]
For the documentation bug, I suggest we add "sbom-tool" prior to the word generate. I understand that how you invoke "sbom-tool" depends on what environment you are running the tool, so perhaps it would make sense to share a couple different example commands based on different environments? 

For the following error message, he is not using the -pn flag, which is required. I tried reproducing this error, but the error that I got was slightly different: 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/55258689/187238217-2fd0c714-122c-4998-b096-b714218f2b97.png">

**Comment by edgarrs** [comment]
I agree with @adriandiglio , let's add the command needed to execute the tool like other places in the documentation. For the second issue, I've seen it when some binaries are missing.

**Comment by edgarrs** [comment]
I confirmed that it is an issue related to our release, I was able to repro it locally. We just moved to .NET 6 which changed the way we need to publish self-contained apps compared to .NET core 3.1, we used before. We are currently investigating how to make our self-contained app work with .NET 6 and in the meantime we removed the affected release in favor of the last working version.

**Comment by edgarrs** [comment]
Fixes for both issues are checked in we are doing additional testing for the new release

**Comment by aasim** [comment]
The new release has been deployed. Please verify by running v0.2.1

**Comment by edgarrs** [comment]
@daneshbadlani can you please try to repro the issue with the new release?

**Comment by edgarrs** [comment]
Danesh was not able to repro the issue anymore
