### ISSUE TITLE
Shared library MonoPosixHelpers not found on MacOS

### ISSUE THREAD

**Issue by ycollet** [microsoft/sbom-tool#123]
I am using a Mac M1 and When I start sbom-tool, I've got an error message telling that shared library MonoPosixHelpers is not found.
MacOS version is 12.5.1

**Comment by edgarrs** [comment]
@ycollet, we had a release that contained a bug that missed some libraries. Can you please try downloading the latest release and see if that works?

**Comment by aasim** [comment]
@ycollet please try version 0.2.1 and confirm if this works now.

**Comment by aasim** [comment]
Fixed in v 0.2.1
