### ISSUE TITLE
Create a SBOM as part this projects build process

### ISSUE THREAD

**Issue by lordneeko** [microsoft/sbom-tool#132]
Creating a SBOM as part of this project does a few things. #1 it provides provence of this tool. #2 it sets the example #3 it provides example output of the tool, which can then be referenced in the readme and used to create create schemas for ingesting the output.

I've noticed that all of the new SBOM vendors that keep popping up since the EO was signed cannot even provide a SBOM of their own software when pressed to do so (CycloneDX, 360,etc).  Set the standard here Microsoft.

**Comment by ByAgenT** [comment]
Our release build process produces SBOM for this tool, you can use it as an example. It is published along with tool binaries in [releases section](https://github.com/microsoft/sbom-tool/releases).
