### ISSUE TITLE
%temp%\GovCompDisc_Log_(stamp).log naming conflicts fail concurrent builds

### ISSUE THREAD

**Issue by AArnott** [microsoft/sbom-tool#134]
The sbom generator evidently creates a temporary file in a shared location, and assigns a timestamp to the filename. But in concurrent builds, second-resolution isn't enough to guarantee uniqueness, and we see builds frequently fail due to log file access conflicts.

For example, this command failed:

> C:\Users\andarno\source\repos\VS-Platform\packages\Microsoft.ManifestTool.CrossPlatform.2.1.31\Content\Microsoft.ManifestTool.dll Generate -b C:\Users\andarno\source\repos\VS-Platform\bin\Shell\Terminal\Setup\x64\Debug\net472\win-x64\ -bc C:\Users\andarno\source\repos\VS-Platform\src\Shell\Terminal\Setup\x64 -pn Terminal.Setup.x64 -pv 1.0.0 -m C:\Users\andarno\source\repos\VS-Platform\bin\Shell\Terminal\Setup\x64\Debug\net472\win-x64\_manifest 

with this error:

> [ERROR] SafelyExecute logged IOException: The process cannot access the file 'C:\Users\andarno\AppData\Local\Temp\GovCompDisc_Log_20220912090327.log' because it is being used by another process.

There were many more project builds that were running similar commands simultaneously. Can the log either be written to a directory we provide at the command line, or can a reliably random suffix be added to the filename to guarantee uniqueness?

**Comment by aasim** [comment]
This log file might be written by the component detectors. @edgarrs to follow up with CD team for resolution.

**Comment by edgarrs** [comment]
@AArnott , this file is created and used by the component detectors, please open an issue here:
https://github.com/microsoft/component-detection/issues/new

**Comment by AArnott** [comment]
@edgarrs Now that the linked bug has been fixed, how will we get an updated SBOM tool that includes that fix?
