### ISSUE TITLE
Supplier field not populated from NuGet packages

### ISSUE THREAD

**Issue by jackdaus** [microsoft/sbom-tool#135]
I am generating an SBOM for a .NET 6 project. I am using the following CLI command:
`.\sbom-tool-win-x64.exe generate -b C:\PublishedCode -bc C:\SourceCode -pn MyProject -pv 1 -ps MyCompany -nsb https://MyCompany.org/MyProject`

But the generated SPDX file is missing the `supplier` data for all the packages. For example, I would expect this NuGet package published by Microsoft to contain the supplier info:

```json
...
"packages": [
    {
      "name": "Microsoft.AspNetCore.Mvc.Razor.Extensions",
      "SPDXID": "SPDXRef-Package-70E748C5551C5B4D727F7DA9E9DCD42666A7ADC25D01187C2817E4FB1FE6B8BA",
      "downloadLocation": "NOASSERTION",
      "filesAnalyzed": false,
      "licenseConcluded": "NOASSERTION",
      "licenseInfoFromFiles": [
        "NOASSERTION"
      ],
      "licenseDeclared": "NOASSERTION",
      "copyrightText": "NOASSERTION",
      "versionInfo": "6.0.8",
      "externalRefs": [
        {
          "referenceCategory": "PACKAGE-MANAGER",
          "referenceType": "purl",
          "referenceLocator": "pkg:nuget/Microsoft.AspNetCore.Mvc.Razor.Extensions%406.0.8"
        }
      ],
      "supplier": "NOASSERTION"
    },
...
```

Is this a bug, or the expected behavior of sbom-tool?

And thanks for your work creating this very useful and easy-to-use tool!

**Comment by aasim** [comment]
We read these values from the NuGet component detector, please open an issue with their repo here: https://github.com/microsoft/component-detection/issues. Once they populate these fields in the detectors, we will pick them up and add it to the sbom.
