### ISSUE TITLE
sbom Validate

### ISSUE THREAD

**Issue by AliceShi789654** [microsoft/sbom-tool#142]
1. run command:
.\sbom-tool-win-x64.exe generate -b $filepath -bc $codepath -pn alicedemo -pv 1.0.0 -ps Alice -nsb https://alicedemo.com -m $manifestpath
2. To generate the file: $manifestpath\_manifest\spdx_2.2\manifest.spdx.json

3. run validate command:
.\sbom-tool-win-x64.exe Validate -b $filepath -o $outputpath -m $manifestpath -mi alicedemo:1.0.0

Error: Encountered error while running ManifestTool validation workflow. Error: The given key 'alicedemo:1.0.0' was not present in the dictionary.

How to fix it?

**Comment by aasim** [comment]
The 'validate' scenario is currently not supported. This tool only generates SBOMs. We are working on a validate solution right now and we should have it ready in a couple of weeks.

**Comment by sebasgomez238** [comment]
Validation is supported now. You can use -mi SPDX:2.2 to validate your SBOM.
