### ISSUE TITLE
Consume ComponentDetection packages from nuget.org

### ISSUE THREAD

**Issue by edgarrs** [microsoft/sbom-tool#149]
https://www.nuget.org/packages?q=Microsoft.componentDetection

**Comment by aasim** [comment]
Also update the version of the CD detectors as part of this work.

**Comment by aasim** [comment]
Delete the public feed once this work is done.

**Comment by edgarrs** [comment]
@aasim , you are already taking care of this, right?

**Comment by edgarrs** [comment]
#162
