### ISSUE TITLE
CLI should allow for reasonable defaults

### ISSUE THREAD

**Issue by richardtallent-erm** [microsoft/sbom-tool#157]
First time using this tool, and I find it frustrating that so many command-line options are required. Most should have reasonable defaults, or be auto-detected. I just spent 10 minutes looking at a the `[INFO] Scan manifest file...` with no indicator of progress, finally hit Enter and got:

```shell
##[error]Encountered an error while generating the manifest.
##[error]Error details: Unable to generate a package version based on provided parameters. Please provide the package version in the 'PackageVersion' parameter.
```

**Comment by edgarrs** [comment]
@daneshbadlani , what are your thoughts on this request?

**Comment by ArgTang** [comment]
+1 for this one. trivy and syft have much easier entrypoint for generating sbom
Any idea why sbom-tool requires all these arguments when competing tools dont?

**Comment by edgarrs** [comment]
@daneshbadlani will come up with a proposal for default values

**Comment by daneshbadlani** [comment]
Provided the default values to @aasim

**Comment by jlperkins** [comment]
Not easily actionable for current team without suggested defaults. A contribution with reasonable suggested defaults would be considered. Currently this work is not planned.

**Comment by richardtallent-erm** [comment]
Looks like @daneshbadlani contributed some reasonable suggested defaults, did those get lost in the shuffle?
