### ISSUE TITLE
Microsoft.ManifestTool fails due to file access collision across processes

### ISSUE THREAD

**Issue by AArnott** [microsoft/sbom-tool#163]
The tool failed with this error while in a parallel build:

> Encountered an error while generating hash for file D:\a\_work\1\s\target\distrib\Setup\ENU\SqlCommon\core.neutral\OSTE3C4.tmp: The process cannot access the file 'D:\a\_work\1\s\target\distrib\Setup\ENU\SqlCommon\core.neutral\OSTE3C4.tmp' because it is being used by another process.

Can this tool be fixed to be safe to call concurrently? e.g. come up with more unique random filenames?

**Comment by aasim** [comment]
@AArnott we don't generate any files while generating the SBOM. We only read the files to generate their checksums. This file is probably being written to by some other process. 

The expectation is that the drop is complete by the time we generate the SBOM. Let me know how we can improve this process to make it work for your case.

**Comment by AArnott** [comment]
> we don't generate any files while generating the SBOM

This error was produced by this tool. #134 is another issue that was fixed and admitted to impact this tool. The bug itself as you can see over there, was in another piece of software, but it's software that is executed by this tool. 
I don't really care which library or sub-tool is responsible for creating these files, because at the end of the day all I have visibility into is that my builds are failing when I run this tool. Like in #134, can some investigation be done to see what sub-part of this tool is responsible for creating these files and move the bug to them, if appropriate?

> The expectation is that the drop is complete by the time we generate the SBOM.

It sounds like this means you don't expect it to run concurrently because it should only run once, at the end. This isn't the case in the model we're using in Visual Studio, where we pack the SBOM up in the same drop with a VSIX (a VS package) and then refer to both in a vsman file that must be built *after* the sbom is built. We also create one sbom per VSIX (more or less), so where we build more than one vsix, we have more than one sbom.

**Comment by jeffkotula** [comment]
Looks like the issue occurs when running against a repo that is currently loaded in Visual Studio. This is a major limitation.
