### ISSUE TITLE
Sbom-tool can scan project with poetry.lock, but wrote 0 package.

### ISSUE THREAD

**Issue by newertp** [microsoft/sbom-tool#172]
When I used sbom-tool to scan the project with poetry.lock, it wrote 0 package elements in the SBOM regardless of source code or docker images. But it seemed that it scanned normally. For detail, please see the screenshot below:

<img width="1334" alt="image" src="https://user-images.githubusercontent.com/20756231/201321759-a30dca12-cebe-49b8-a451-dc0d29e1ed0a.png">

The command is as follows:
For source code:
salus Generate -b ./test -bc ./test -pn Test -pv 0.0.1 -ps test -nsb https://test.com/ -V Verbose -m .
For docker image:
salus Generate -b ./test -bc ./test -di test:latest -pn Test -pv 0.0.1 -ps test -nsb https://test.com/ -V Verbose -m .

ENV: Ubuntu-20.04

**Comment by edgarrs** [comment]
We have new detectors being executed and we are not writing packages in the SBOM. Let's add the new component mappings into the sbom-tool

**Comment by ksigmund** [comment]
Poetry components are either Pip or Git.  I am investigating, but at the moment it doesn't appear that any of the detected components are returned for the SBOM Tool from the detectors.

**Comment by ksigmund** [comment]
Poetry is currently marked as Beta/Experimental and for those types of components, results are not returned from the component detection library.  Because of this, they will not be recorded in the SBOM.

https://github.com/microsoft/component-detection/blob/main/src/Microsoft.ComponentDetection.Detectors/poetry/PoetryComponentDetector.cs#L16

**Comment by ksigmund** [comment]
> Component detectors implementing this interface are in an experimental state.
> The detector processing service guarantees that:
>   They should NOT return their components as part of the scan result or be allowed to run too long (e.g. 4 min or less).
>   They SHOULD submit telemetry about how they ran.
> If opted in, they should behave like a normal detector.

https://github.com/microsoft/component-detection/blob/main/src/Microsoft.ComponentDetection.Contracts/IComponentDetector.cs#L53-L59
