### ISSUE TITLE
Additionally add SHA512 checksum to SBOM

### ISSUE THREAD

**Issue by anotherbridge** [microsoft/sbom-tool#180]
When running the command
```
sbom-tool generate -b ./ -bc ./ -pn <package name> -pv <package version> -ps <package supplier> -nsb <namespace uri base> -D true
```
the resulting SBOM creates the SHA1 & and SHA256 hashes of all the files in the package considered. However, I additionally want to have the SHA512 in that list. 

From the documentation that is present so far and the CLI-reference I cloudn't find a way to modify this default behavior. What I would imagine is that this could maybe done with a `config.json` file.  
Is this correct? If yes, how should this file be structured? Is there any documentation on that? If no, then I would be interested on how to do this?

**Comment by daneshbadlani** [comment]
@anotherbridge Hey, I would love to understand what's your use case here for SHA512? What are you exactly trying to accomplish with the SHA512 hash?

**Comment by anotherbridge** [comment]
@daneshbadlani Hi, thanks for your response. 

According to the SPDX specification in ISO/IEC 5962:2021 the SHA512 hash is a valid algorithm to be used. Further the following hashes are valid according to that norm: 
- SHA1
- SHA224
- SHA256
- SHA384
- SHA512
- MD2
- MD4
- MD5
- MD6

Especially we want to use the [SHA3](https://en.wikipedia.org/wiki/SHA-3) version, i.e. SHA3-512, due to the fact that we have the requirement of not using any broken hash functions. 

Does that help you?

**Comment by anotherbridge** [comment]
Since the SHA-2 has the same underlying math as SHA-1 it also shares the flaws. Additionally, in 2015 NIST made the SHA-3 an official [recommended standard](https://www.nist.gov/news-events/news/2015/08/nist-releases-sha-3-cryptographic-hash-standard).

We want to follow the recommendations of the [NIST](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.202.pdf):
> The four SHA-3 hash functions are alternatives to the SHA-2 functions, and they are designed to
provide resistance against collision, preimage, and second preimage attacks that equals or
exceeds the resistance that the corresponding SHA-2 functions provide.

**Comment by THEJRRR** [comment]
Added to bug backlog - closing here
