### ISSUE TITLE
VCPKG integration

### ISSUE THREAD

**Issue by MFaisalZaki** [microsoft/sbom-tool#191]
Based on [issue #81](https://github.com/microsoft/sbom-tool/issues/81), is it possible to generate sbom from [vcpkg](https://github.com/microsoft/vcpkg) on MS Windows.

Thanks.

**Comment by adriandiglio** [comment]
Hello @MFaisalZaki , please see VCPKG's documentation on generating SBOMs https://github.com/data-queue/vcpkg-docs/blob/software-bill-of-materials/vcpkg/reference/software-bill-of-materials.md
