### ISSUE TITLE
Publish container image to MCR

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/sbom-tool#195]
A `Dockerfile` is now available, as of #110. To make adoption easier, this should be built and published to the Microsoft Container Registry (MCR).

Onboarding instructions can be found at https://aka.ms/mcr/onboarding.

**Comment by aasim** [comment]
1. Upload image to MCR
2. Add documentation on how to use it.

**Comment by edgarrs** [comment]
Dup #196

**Comment by CameronGo** [comment]
Am I missing something? I searched MCR for SBOM and I don't see anything on the public site. https://mcr.microsoft.com/en-us/catalog?search=SBOM

When I attempt to access the link provided above (https://aka.ms/mcr/onboarding) it requires authorization which I don't have. Is this feature intended to provide a public docker image for use?

**Comment by edgarrs** [comment]
@CameronGo, we are tracking this work in a different issue #196
