### ISSUE TITLE
Publish to package manager registries

### ISSUE THREAD

**Issue by JamieMagee** [microsoft/sbom-tool#196]
Currently, all the install methods for `sbom-tool` are to come to this repo and download the tool from the releases. I think it would be much more user friendly to publish it as a package to package manager registries.

- [x] Windows
  - [x] [winget](https://github.com/microsoft/winget-pkgs)
  	- https://github.com/microsoft/winget-pkgs/pull/118723
- [x] macOS
  - [x] [Homebrew](https://brew.sh/)
    - https://github.com/Homebrew/homebrew-core/pull/137155
- [ ] Linux
  - [ ] RPM-based distros (Mariner, RHEL, etc.)
    - [Onboarding instructions for `package.microsoft.com`](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/pmc-package-ingestion/pmc-onboardingreference/index)
    - https://github.com/microsoft/CBL-Mariner
  - [ ] DEB-based distros (Debian, Ubuntu, etc.)
    - [Onboarding instructions for `package.microsoft.com`](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/pmc-package-ingestion/pmc-onboardingreference/index)
  - [ ] Alpine
    - https://gitlab.alpinelinux.org/alpine/aports
    - https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package
  - [ ] Arch Linux
    - https://archlinux.org/
    - https://aur.archlinux.org/
    - https://wiki.archlinux.org/title/Arch_User_Repository
  - [ ] NixOS
    - https://nixos.org/
    - https://github.com/NixOS/nixpkgs
    - [Initial package in a branch](https://github.com/JamieMagee/nixpkgs/tree/sbom-tool-1.5.2)
- [ ] Docker
	- [ ] [Microsoft Container Registry (MCR)](https://aka.ms/mcr/onboarding)

The above is a bit of a brain dump of links and resources, but not exhaustive.

**Comment by shawnfunke** [comment]
A Formulae for Homebrew has been added to the core tap at Homebrew/homebrew-core#137155, please note that at this time it only supports the `x86_64` architecture until the issue described at #223 has been resolved.

**Comment by JamieMagee** [comment]
I created a PR in the winget-pkgs repository: https://github.com/microsoft/winget-pkgs/pull/118723

I'll need to follow-up with a GitHub Actions workflow to automatically add the new manifest when we publish a new version here. See https://github.com/vedantmgoyal2009/winget-releaser

**Comment by JamieMagee** [comment]
The winget PR was merged, and it can be installed with `winget install Microsoft.SBOMTool`:

https://github.com/microsoft/sbom-tool/assets/1358764/a53e2bac-7244-418a-b3df-1a2c21a63502

I still need to:
- Automate the winget update
- Update our documentation

**Comment by JamieMagee** [comment]
Added documentation here: https://github.com/microsoft/sbom-tool/pull/368

**Comment by THEJRRR** [comment]
If the community were interested, we would consider accepting a contribution.
