### ISSUE TITLE
DotnetTool package type cannot be installed by Guardian

### ISSUE THREAD

**Issue by chrisnielsen-MS** [microsoft/sbom-tool#199]
When attempting to install the package via Nuget, we get the following error:

Warning: Failed to install from source https://pkgs.dev.azure.com/secdevtools/_packaging/SecDevTools/nuget/v3/index.json with exception NuGet.Packaging.Core.PackagingException: Package 'Microsoft.Sbom.DotNetTool 0.2.5' has a package type 'DotnetTool' that is not supported by project 'C:\Repos\actions-runner\_work\_msdo\packages\nuget'.

Can another package be produced that either leaves the package type unset, or specifies it as 'Dependency'? More details here: https://learn.microsoft.com/en-us/nuget/create-packages/set-package-type?tabs=dotnet

**Comment by aasim** [comment]
@chrisnielsen-MS this sounds like an error on your project. Does your project type support dotnet tools? If not, you may be better off using the nuget package instead. I am closing this ticket, if you have any questions please reopen.

**Comment by chrisnielsen-MS** [comment]
@aasim the other nuget package (Microsoft.Sbom.Tool) is framework-dependent and so is also unsuitable for use in Guardian. We need a package that is self-contained but also is not of type 'DotnetTool'.
