### ISSUE TITLE
Validate Cannot Parse SBOMs Generated by Microsoft.SBOMTool-2.0.104

### ISSUE THREAD

**Issue by elantiguamsft** [microsoft/sbom-tool#205]
Unable to validate SBOMs generated by Microsoft.SBOMTool-2.0.104 (See creationInfo field in SBOM). Validation works fine with SBOMs created with v2.1.35 of the tool. 

Can repro by running validate on 2.0.104SBOMDrop folder shared [here](https://microsoft-my.sharepoint.com/:f:/p/elantigua/EjL6bOZimb5Nhd0JIL8QsYgBunzU3i06-xjz6ToVDD5jmw?e=6ovNql).

Usage/Error Info:
PS D:\prj> .\sbom-tool.exe validate -b D:\TestDrops\2.0.104SBOMDrop -o D:\cvo.json -verbosity verbose -mi spdx:2.2 -m D:\TestDrops\2.0.104SBOMDrop\_manifest\
##[verbose]Adding root path filter valid paths
##[debug]Enumerating files under the root path D:\TestDrops\2.0.104SBOMDrop.
##[debug]Splitting the workflow into 8 threads.
##[debug]Waiting for the workflow to finish...
##[debug]Splitting the workflow into 8 threads.
##[debug]Waiting for the workflow to finish...
##[error]Encountered an error while validating the drop.
##[error]Error details: Parser has reached the Finished state while we are still processing some properties.
##[information]Finished execution of the Validate workflow SBOMTelemetry {Result=Failure, Errors=ErrorContainer`1 {Count=0, Errors=[]}, Parameters=Configuration {BuildDropPath=ConfigurationSetting`1 {Value="D:\\TestDrops\\2.0.104SBOMDrop", Source=CommandLine, IsDefaultSource=False}, BuildComponentPath=null, BuildListFile=null, ManifestPath=null, ManifestDirPath=ConfigurationSetting`1 {Value="D:\\TestDrops\\2.0.104SBOMDrop\\_manifest\\", Source=CommandLine, IsDefaultSource=False}, OutputPath=ConfigurationSetting`1 {Value="D:\\cvo.json", Source=CommandLine, IsDefaultSource=False}, Parallelism=ConfigurationSetting`1 {Value=8, Source=Default, IsDefaultSource=True}, Verbosity=ConfigurationSetting`1 {Value=Verbose, Source=CommandLine, IsDefaultSource=False}, ConfigFilePath=null, ManifestInfo=ConfigurationSetting`1 {Value=[ManifestInfo {Name="spdx", Version="2.2"}], Source=CommandLine, IsDefaultSource=False}, HashAlgorithm=ConfigurationSetting`1 {Value=AlgorithmName {Name="SHA256"}, Source=Default, IsDefaultSource=True}, RootPathFilter=null, CatalogFilePath=null, ValidateSignature=ConfigurationSetting`1 {Value=False, Source=CommandLine, IsDefaultSource=False}, IgnoreMissing=ConfigurationSetting`1 {Value=False, Source=CommandLine, IsDefaultSource=False}, ManifestToolAction=Validate, PackageName=null, PackageVersion=null, PackageSupplier=null, FilesList=null, PackagesList=null, TelemetryFilePath=null, DockerImagesToScan=null, ExternalDocumentReferenceListFile=null, AdditionalComponentDetectorArgs=null, NamespaceUriUniquePart=null, NamespaceUriBase=null, GenerationTimestamp=null, FollowSymlinks=ConfigurationSetting`1 {Value=True, Source=Default, IsDefaultSource=True}, DeleteManifestDirIfPresent=ConfigurationSetting`1 {Value=False, Source=Default, IsDefaultSource=True}}, SBOMFormatsUsed=[SBOMFile {SbomFormatName=ManifestInfo {Name="SPDX", Version="2.2"}, SbomFilePath="D:\\TestDrops\\2.0.104SBOMDrop\\_manifest\\spdx_2.2\\manifest.spdx.json", FileSizeInBytes=24651}], Timings=[Timing {EventName="Total validation time", TimeSpan="00:00:00.0474186"}], Switches={}, Exceptions={["Microsoft.Sbom.Exceptions.ParserException"]="Parser has reached the Finished state while we are still processing some properties."}}
PS D:\prj>

**Comment by aasim** [comment]
In older SBOM generators, we would skip adding the externalDocumentReference section all together if it was missing, now we add an empty array if there are no references. The validator needs to be aware of this, and should skip if there is no external document reference section
