### ISSUE TITLE
add option for CycloneDX format

### ISSUE THREAD

**Issue by mieliespoor** [microsoft/sbom-tool#210]
The two leading formats for SBOM are
- CycloneDX
- SPDX

Both these are ISO approved so it would be great if this tool could provide the option to generate both. I do note the discussion here: https://github.com/microsoft/sbom-tool/discussions/48, but I do feel this tool would have an advantage if it can be format agnostic.

An advantage of generating CycloneDX format would be the ease of integrating with a tool like DependencyTrack whom are strongly against SPDX which a rival format to their own (OWASP) developed CycloneDX  https://github.com/DependencyTrack/dependency-track/discussions/1222

**Comment by daneshbadlani** [comment]
Thanks for your feedback. However, we have decided to focus on SPDX format for the SBOM generation, and as Aasim mentioned you can extend our tool to generate a CycloneDX format SBOM. But please feel free to leverage the [component detector](https://github.com/microsoft/component-detection/tree/main) to build a CycloneDX format SBOM generator yourself.
