### ISSUE TITLE
SBOMTool produces invalid SPDX SBOM file for supplier for PowerShell

### ISSUE THREAD

**Issue by surendrapathak** [microsoft/sbom-tool#217]
### Steps to reproduce

SBOM included with the released artifact is does not confer to SPDX2.2 specification

https://github.com/PowerShell/PowerShell/releases/download/v7.3.3/powershell-7.3.3-osx-x64.tar.gz

As per [specification](https://spdx.github.io/spdx-spec/v2.2.2/package-information/#75-package-supplier-field), `PackageSupplier` value should start with `Person:`, `Organization:` or `NOASSERTION`.

However, on line 10959 and 11837, the value of supplier exists without those prefixes. 

```  
"supplier": "Microsoft/GitHub"
```

### Expected behavior

```console
SBOM adheres to SPDX spec 2.2
```

### Actual behavior

```console
"supplier": "Microsoft/GitHub"
```
```


### Error details

```console
NA
```

### Environment data

```powershell
NA
```

### Visuals

NA

### Others
At Powershell - https://github.com/PowerShell/PowerShell/issues/19211
Analysis Tool - [sbomqs - Quality metrics for SBOMs](https://github.com/interlynk-io/sbomqs/)

**Comment by edgarrs** [comment]
Fixed
