### ISSUE TITLE
how to make the sbom-tool works against a apache ant project.

### ISSUE THREAD

**Issue by torlix** [microsoft/sbom-tool#245]
I tried to scan a apache ant project, but nothing scanned.

**Comment by edgarrs** [comment]
What is the command a parameters that you are running and what is the error you are getting?

**Comment by edgarrs** [comment]
@torlix, what are the command and parameters that you are running and what is the error you are getting?

**Comment by edgarrs** [comment]
We don't have enough information to take an action.
