### ISSUE TITLE
Scanning Docker image with conda dependencies

### ISSUE THREAD

**Issue by datdo-msft** [microsoft/sbom-tool#254]
Hi,

I'm trying to scan a docker image with conda dependencies set using the -di option and passing it the corresponding image name. However, looking at the generated SBOM, I do not see any of the conda dependencies (packages) being captured.

I'm also seeing this log line from the console output: "[INFO] No compatible Conda installation found on system. Conda detection will not run." -- I assume this probably has something to do with it? If so, do I need Conda to be installed on the local host that the tool is running on or inside the docker image it's scanning? Thanks!

**Comment by aasim** [comment]
Yes, we run the detectors built by CG team to detect components. That error is why you are not seeing any conda packages.
As you can see in this table, conda detection requires conda to be installed https://github.com/microsoft/component-detection/blob/1cb405dafda842144ea50b2dc9682e9664052b03/docs/feature-overview.md

**Comment by datdo-msft** [comment]
Thanks for the prompt response. But could you specify where conda needs to be installed? Does it need to be installed on the local host where the tool is being invoked? Or does it need to be installed inside the docker image that's being scanned?
