### ISSUE TITLE
Can the tool not use docker under the hood to scan docker images?

### ISSUE THREAD

**Issue by datdo-msft** [microsoft/sbom-tool#259]
Hi,

We are trying to use this tool to scan docker images from within a docker container. However, it seems that the tool spins up a docker container under the hood itself as part of its image scanning process. This currently cannot work for our scenario in AzureML since the environment in which we're invoking the tool is inside a docker container already. Is there a way for the tool to scan packages in a docker image without using docker (ie, spinning up a docker container) under the hood? This is currently blocking our integration in AzureML.

Thanks!

**Comment by adriandiglio** [comment]
The SBOM-Tool uses Component Detection https://github.com/microsoft/component-detection, and Component Detection currently uses Syft for docker containers. https://github.com/anchore/syft
