### ISSUE TITLE
Use updated version of component-detection

### ISSUE THREAD

**Issue by anotherbridge** [microsoft/sbom-tool#270]
As mentioned in issue #268, there is a problem with some Python packages and specified versions in a `requirements.txt` file. 

@edgarrs Since you mentioned that this is probably an issue with the component-detection tool that you are using, I opened an issue there and got the response that with the current version this is problem is not present (c.f. [Issue #590 of component-detection](https://github.com/microsoft/component-detection/issues/590)). 

Thus I assume you probably use an outdated version of that tool. 

Could you please update the version to resolve the issue #268?

**Comment by ryanbrandenburg** [comment]
We have updated to the most recent version of the CD libraries.
