### ISSUE TITLE
Unable to run the tool after version 0.3.3 / Some services are not able to be constructed

### ISSUE THREAD

**Issue by TimHeinrich** [microsoft/sbom-tool#278]
This is how I try to use the tool (and which is working with version 0.3.3) on a Windows 10 Enterprise 21H2 machine:

> dotnet tool install --global Microsoft.Sbom.DotNetTool
> sbom-tool generate -b ..\drop -bc .\ -ps name -pv 1.3 -pn Test -nsb something.something

This is the error that is thrown with the current version:

`Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.BoolConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.BoolConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.BoolConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.HashAlgorithmNameConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.HashAlgorithmNameConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.HashAlgorithmNameConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.IntConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.IntConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.IntConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.LogEventLevelConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.LogEventLevelConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.LogEventLevelConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.ManifestInfoConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.ManifestInfoConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.ManifestInfoConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.NullableBoolConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.NullableBoolConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.NullableBoolConfigurationSettingAddingConverter'.) (Error while validating the service descriptor 'ServiceType: Microsoft.Sbom.Api.Config.ValueConverters.StringConfigurationSettingAddingConverter Lifetime: Transient ImplementationType: Microsoft.Sbom.Api.Config.ValueConverters.StringConfigurationSettingAddingConverter': Unable to resolve service for type 'Microsoft.Sbom.Common.Config.SettingSource' while attempting to activate 'Microsoft.Sbom.Api.Config.ValueConverters.StringConfigurationSettingAddingConverter'.)`

Am I somehow using the tool wrong or is this an issue with the software?

**Comment by edgarrs** [comment]
Hi @TimHeinrich, which version of the package are you using?

**Comment by TimHeinrich** [comment]
@edgarrs I tried with all versions after 0.3.3, none of them are functional for me. The error message posted is from the most recent version 1.1.5

**Comment by edgarrs** [comment]
@TimHeinrich , I was able to successfully install and execute the latest version of the tool. Which version of dotnet do you have install? Run dotnet --version

**Comment by TimHeinrich** [comment]
@edgarrs Dotnet --version gives me 7.0.304

**Comment by edgarrs** [comment]
Can you please the output of dotnet --info?

**Comment by ksigmund** [comment]
Please also run `dotnet --list-sdks`

**Comment by TimHeinrich** [comment]
@edgarrs @ksigmund

```powershell
dotnet --list-sdks
7.0.200 [C:\Program Files\dotnet\sdk]
7.0.304 [C:\Program Files\dotnet\sdk]
``` 

```powershell
dotnet --info
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.200 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by ryanbrandenburg** [comment]
We're curious if you're running into this issue on multiple machines or just one because it sounds like it might be a "machine state" issue.

**Comment by TimHeinrich** [comment]
Finally had some time to test it on my private machine, and there it actually works, so it seems like some kind of "machine state" error on my work notebook, but I have no idea where to look further

**Comment by adriandiglio** [comment]
Closing, as this seems related to your specific environment. Please reopen if you believe otherwise.

**Comment by Rich-Ott** [comment]
For anyone else coming across this error in the future, I was also running into the exact same issue on my development machine. 

I found out that it's because I had `DOTNET_ENVIRONMENT=Development` set in my user environment variables. Temporarily removing that environment variable allowed `sbom-tool` to run correctly.

**Comment by NinjaCross** [comment]
> For anyone else coming across this error in the future, I was also running into the exact same issue on my development machine.
> 
> I found out that it's because I had `DOTNET_ENVIRONMENT=Development` set in my user environment variables. Temporarily removing that environment variable allowed `sbom-tool` to run correctly.

I confirm, this solved the problem for me too.
I personally think this should be considered a bug... why should the behaviour of a global tool be compromised by DOTNET_ENVIRONMENT ?
