### ISSUE TITLE
Outdated Microsoft Component Detector

### ISSUE THREAD

**Issue by BlackyTheDruide** [microsoft/sbom-tool#283]
Hi,

currently we are working on integration the SBOM Tool into our development environment. In this process we faced the problem that we are going to need a new detector. We tried to create a new detector and use it via "--AdditionalPluginDirectories" parameter. During our analysis we have noticed that this parameter will be gone once an updated version of the Microsoft Component Detector is used. 

So are there any future plans to update the used version of Component detection and if so, are there any suggestions on how to provide additional Detectors which are not directly provided by the component detection?

**Comment by JamieMagee** [comment]
Hi @BlackyTheDruide,

Unfortunately, we removed that parameter in Component Detection as we weren't able to find anyone using it, and it added a lot of developer overhead.

Instead, we tried to make the process to upstream new detectors easier. I can help if you're interested in contributing it back to Component Detection. What sort of packages is the detector for?
