### ISSUE TITLE
NuGET Packages license informations missing

### ISSUE THREAD

**Issue by ekomsctr** [microsoft/sbom-tool#286]
Hello,

first of all nice tool! It came out right when a customer asked for this!
I integrated this tool using Post Build Events in visual studio, and everything works great! The only thing i noticed is that, for the referenced NuGet packages by my project, the license informations are missing (though the library in question, Nmodbus4, does specify it).

I found this related issue ( #122 ), and following the discussion i found out that the Microsoft.ComponentDetection team agreed that it should be a SBOM-tool responsability to retrieve licensing informations for the packages, as their component is focused on building the dependency graph.

I would like to know if there are any plans to support this, as this is an interesting tool to use.

Thanks in advance, 
Roberto

**Comment by daneshbadlani** [comment]
@ekomsctr Thank you for reaching out to us. Adding license information is in our feature backlog, however, we do not have an estimated timeline on when it will be done as we are working on other higher priority items.

**Comment by ekomsctr** [comment]
> @ekomsctr Thank you for reaching out to us. Adding license information is in our feature backlog, however, we do not have an estimated timeline on when it will be done as we are working on other higher priority items.

Thank you very much for the answer! This tool is just so useful, so it would be great if possible to have most of the NOASSERTION informations compiled (if available of couse).

I'm no expert in developing CLI tools such as this, but definitely will be looking if i manage to get a pull request up sometime in the future!

**Comment by ekomsctr** [comment]
Also, i would also to integrate a question about how would this be implemented, via a license.txt file for example? Is there any standard regarding this?

This could be helpful in setting a standard if not already existing: https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packing-a-license-expression-or-a-license-file

**Comment by edgarrs** [comment]
Done

**Comment by sebasgomez238** [comment]
@ekomsctr If you want to start populating license information you can now add the -li parameter like this:

`generate -b {PathToADirectory} -bc {PathToADirectory} -ps sample -pv 1.0.0 -pn sample -li true`

This will fetch license information from the open source ClearlyDefined API and populate the licenseConcluded field of the packages section.
