### ISSUE TITLE
Generated SBOM is not recognized in Blackduck & FOSSA tool

### ISSUE THREAD

**Issue by akhilsudan** [microsoft/sbom-tool#287]
![image](https://github.com/microsoft/sbom-tool/assets/38279426/f6cc3f97-f300-4477-9e33-a8ad2cc9ba8a)

![image](https://github.com/microsoft/sbom-tool/assets/38279426/eefd64cf-a1e1-4e7b-abed-be99b2914fad)

![image](https://github.com/microsoft/sbom-tool/assets/38279426/bbeb8d32-85c8-402b-9326-04c641dbbea1)

**Comment by edgarrs** [comment]
Unfortunately, we are not aware of what those tools expect as inputs so we recommend following up with the owners of the tools to understand what the issue is.
