### ISSUE TITLE
SPDX output is not valid using spdx-tools

### ISSUE THREAD

**Issue by spr0ut** [microsoft/sbom-tool#289]
The output generated is not a valid SPDX 2.2 format when validated using SPDX tooling from https://github.com/spdx

**Steps to reproduce**
- Create simple console app, add single dependecy (e.g. Newtonsoft.Json) and build.
- Run sbom-tool `sbom-tool generate -b .\bin\Debug\net6.0 -bc . -pn console -pv test -ps test`
- Validate output using either web validator
https://tools.spdx.org/app/validate/ or https://github.com/spdx/tools-python
`pyspdxtools -i ScanManifest_20230717130140229.json`

ScanManifest is missing creationInfo, documentNamespace, documentDescribes fields.

**Comment by sebasgomez238** [comment]
@spr0ut I followed your example and used the web validator and it successfully validated the manifest.spdx.json file from our output. creationInfo, documentNamespace, and documentDescribes are all present in the manifest. 

`sbom-tool generate -b "C:\Desktop\ConsoleAppGenerate\bin\Debug\net6.0" -bc "C:\Desktop\ConsoleAppGenerate" -ps test -pn test -pv 1`

This places an _manifest folder in the -b path and it contains both the manifest (manifest.spdx.json) and the hash of the manifest (manifest.spdx.json.sha256).
