### ISSUE TITLE
Latest release v1.3.2 is missing assets for builds?

### ISSUE THREAD

**Issue by tpodowd** [microsoft/sbom-tool#296]
The binary download from the release assets is not working as the latest release is missing build assets. It also seems to be mis-versioned? v1.3.2 vs the tag which is v1.2.1 ?

https://github.com/microsoft/sbom-tool/releases/tag/v1.2.1

**Comment by adriandiglio** [comment]
Our release of 1.3.2 has the assets there now https://github.com/microsoft/sbom-tool/releases/tag/v1.3.2. If you discover another issue, please feel free to reopen this.
