### ISSUE TITLE
sbom tool does not scan Linux file system unless its a docker image

### ISSUE THREAD

**Issue by romahamu** [microsoft/sbom-tool#297]
Hello,

SBOM tool uses component-detection tool to get the dependencies and for Linux it seems only way is passing docker image to the tool.

i.e if we have to scan local filesystem then it does not generate SBOM for it as there are no components found. 

I have created a ticket for component-detection tool here https://github.com/microsoft/component-detection/issues/691

**Comment by adriandiglio** [comment]
As you noticed, Component Detection (CD) is the source for this capability. Once Component Detection supports it, the SBOM Tool just needs to update to the latest version of CD to incorporate the changes. Thanks for bringing it to their attention!
