### ISSUE TITLE
Invoke-WebRequest not working for downloading latest version

### ISSUE THREAD

**Issue by Chicoo** [microsoft/sbom-tool#299]
When using the command Invoke-WebRequest -Uri https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-win-x64.exe -OutFile sbom-tool.exe an error is thrown 

Invoke-WebRequest : The request was aborted: The connection was closed unexpectedly.
At line:1 char:1
+ Invoke-WebRequest -Uri https://github.com/microsoft/sbom-tool/release ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest
   ) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands
   .InvokeWebRequestCommand

When pasting the url ( https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-win-x64.exe) in a browser it is redirected (https://github.com/microsoft/sbom-tool/releases/download/v1.2.1/sbom-tool-win-x64.exe) and this gives a 404 Not Found error.

**Comment by adriandiglio** [comment]
Thanks! We just fixed this. Apparently, we were missing artifacts in our latest release (here is a related issue https://github.com/microsoft/sbom-tool/issues/296) but this has been addressed now. Please try again, and reopen this Issue if something is still giving you an error.
