### ISSUE TITLE
Suggestion - Add a Quick Start Guide for the sbom-tool to the SPDX Quick Start folder

### ISSUE THREAD

**Issue by goneall** [microsoft/sbom-tool#301]
We just created a new folder for quick start guides open to any tools that generate or consume SPDX documents.

In one of our SPDX community calls, it was suggested that the sbom-tool have one (or more) quick starts added to the folder.

We plan on promoting quick starts in this folder as part of our overall SPDX adoption program.

See the [quick start guide](https://github.com/spdx/outreach/tree/main/quickstart) for context and info.

There is also an issue in the quick start repo to track this request: https://github.com/spdx/outreach/issues/28

**Comment by THEJRRR** [comment]
@adriandiglio - what are we doing with this request?

**Comment by adriandiglio** [comment]
@THEJRRR This suggestion could potentially improve the visibility/discoverability of our tool. It's something we could opportunistically do, but is low on the priority list. But having our sbom-tool documentation in multiple places makes it harder to maintain.
