### ISSUE TITLE
Questions about generating SBOM using the sbom-tool

### ISSUE THREAD

**Issue by yukaizhao1** [microsoft/sbom-tool#391]
Hello, recently we've been trying to use the sbom-tool, which is a very user-friendly tool. However, what piqued our curiosity is whether the sbom-tool only analyzes dependency files. If we have the source code of a project and dependency files but haven't compiled the project or installed related dependencies, can the sbom-tool still generate an SBOM?
In fact, when we attempted to generate an SBOM for the java-tomcat-maven-example (https://github.com/daticahealth/java-tomcat-maven-example), we encountered some difficulties. The sbom-tool failed to detect any relevant dependencies. Here is the command we used:
```
sbom-tool generate -b /home -bc /home/java-tomcat-maven-example-master -pn example1 -pv version1 -ps sbom-test
```
The system version is Ubuntu 20.04.

**Comment by yukaizhao1** [comment]
Or could it be related to the current network conditions, as I performed the above tasks in a situation of poor network connectivity?

**Comment by edgarrs** [comment]
The sbom-tool is a build-time SBOM generator. The tool expects a minimum of package restore to be able to identify the dependencies. The SBOM also contains a section where it enumerates the build output files, if there is no build, this section would be empty. Let us know if you have further questions.
