### ISSUE TITLE
NamespaceBaseURI is still required if using API.

### ISSUE THREAD

**Issue by sebasgomez238** [microsoft/sbom-tool#396]
If the following RuntimeConfiguration object is passed to the `GenerateSbomAsync` method of the API:

`RuntimeConfiguration configuration = new RuntimeConfiguration()
{
    DeleteManifestDirectoryIfPresent = true,
    WorkflowParallelism = 8,
    Verbosity = System.Diagnostics.Tracing.EventLevel.Warning,
    NamespaceUriBase = null,
};`

An error is thrown saying -nsb cannot be null. This does not match with the current behavior of the tool where -nsb is optional and if it is not provided a unique one will be generated for the SBOM.

**Comment by edgarrs** [comment]
NamespaceBaseURI must be explicitly specified
