### ISSUE TITLE
Documentation Spelling Issues in Arguments Markdown

### ISSUE THREAD

**Issue by robertcrockett** [microsoft/sbom-tool#412]
The SBOM arguments markdown file contains several spelling issues. Proposing the following changes:
 

Line 17: Validate section - manifest
- ...certificate of the manfiest.
+ ...certificate of the manifest.
 
Line 26: CatalogFilePath section - Add a space after sentence
- ...standard directory structure.The path
+ ...standard directory structure. The path
 
Line 60: BuildListFile - included
- ...will be inlcuded in the generated manifest.
+ ...will be included in the generated manifest.
 
Line 76: AdditionalComponentDetectorArgs - representing
- respresenting command-line switches.
+ representing command-line switches.

**Comment by sebasgomez238** [comment]
Thank you for you contribution! Closing this as your PR has been merged.
