### ISSUE TITLE
Add another Validate method to SBOMValidator that accepts the SBOM to validate

### ISSUE THREAD

**Issue by micyunmsft** [microsoft/sbom-tool#417]
Currently SBOMValidator only has one Validate method, but this method does not allow you to pass in the SBOM to validate. Please add another Validate method to this class that can accept the SBOM to validate.

https://github.com/microsoft/sbom-tool/blob/d2627c021c36edb38b3e1f6f370be9fbf99ed43b/src/Microsoft.Sbom.Api/SBOMValidator.cs#L25

**Comment by sebasgomez238** [comment]
This method was added in v1.7.1
