### ISSUE TITLE
DLL version numbers

### ISSUE THREAD

**Issue by sphengle** [microsoft/sbom-tool#428]
We have a number of common DLLs that we have created in-house and these are added as normal references.  The SBOM tool doesn't seem to pick up the version numbers of these references.  For us this is actually the most useful item of SBOM information.

**Comment by sphengle** [comment]
> How are the DLLs added? Are they referenced in csproj files? Could you provide an example?

There common DLLs are located on a network drive.  In the csproj files they appear something like the following...

<Reference Include="Blah.Blah">
      <HintPath>X:\blah\blah\blah.dll</HintPath>
    </Reference>

**Comment by JamieMagee** [comment]
Ah, currently we don't support DLLs directly, but only those loaded as NuGet packages.

**Comment by sphengle** [comment]
> Ah, currently we don't support DLLs directly, but only those loaded as NuGet packages.

That's a shame.  About half of our references are those of components we have created in-house.  So looks like we won't be able to create an SBOM with this tool.

**Comment by JamieMagee** [comment]
We use https://github.com/microsoft/component-detection library to do the underlying scanning. Could you open an issue there to track this please?

**Comment by adriandiglio** [comment]
Hi @sphengle, our SBOM generation tool has two main sections that we populate: The Files section (which lists Files produced from the build), and the Packages section (which lists the language package dependencies, such as NuGet, used within your application). 

Per the SPDX 2.3 spec, the Files section does not have a field to capture versions, and today, this is where .DLL files are captured. Only the Packages section (per SPDX spec) has a version field. The Packages section is expected to identify language package dependencies (things that a consumer can look up CVE vulnerabilities for). I don't believe the Packages section should contain .DLLs based on conversations that I've been having with industry peers in CISA weekly working groups. 

I hope this helps.
