### ISSUE TITLE
Can't compile due to private NuGet feed

### ISSUE THREAD

**Issue by patriksvensson** [microsoft/sbom-tool#45]
When doing a package restore, I see a lot of 401 responses from some package source that's in use.
Any idea what I should do to be able to compile this?

```
C:\Program Files\dotnet\sdk\3.1.421\NuGet.targets(128,5): error : Response status code does not indicate success: 401 (Unauthorized - TF400813: Resource not available for anonymous access. Client authentication required. (DevOps Activity ID: 9C792FB8-970D-431E-9CB6-887C3CD827C8)). [REDACTED\microsoft\sbom-tool\Microsoft.Sbom.sln]
```

**Comment by HowardvanRooijen** [comment]
Isn't the `nuget.config` in the repo root pointing to a private package feed?

**Comment by patriksvensson** [comment]
@HowardvanRooijen Yes! Removing the nuget.config makes it compile.

**Comment by aasim** [comment]
The feed mentioned in the nuget.config is a public feed, and it doesn't need authentication, but it might be missing some packages that your specific build environment requires. We are in the process of moving all our required packages to nuget.org after which this public feed won't be required.

Can you please send me your build environment and .net sdk versions and I will make sure that all those packages are there in the public feed to unblock you all.

@patriksvensson @HowardvanRooijen

**Comment by patriksvensson** [comment]
Not sure why you closed this, to be honest. The problem is the Nuget.config in the root (which you should remove). I have all the required SDK:s to build this.
