### ISSUE TITLE
Add composer.json as source for SBOMs

### ISSUE THREAD

**Issue by JuergenGutsch** [microsoft/sbom-tool#478]
Composer is a dependency manager for PHP

Would be cool to also create an SBOM out of composer.json files:
https://getcomposer.org/

Thanks,

**Comment by sebasgomez238** [comment]
@JuergenGutsch this would be more of an ask for the https://github.com/microsoft/component-detection repo. They provide the underlying library that detects components. We then use the result of that scan to generate the SBOM.

**Comment by JuergenGutsch** [comment]
@sebasgomez238 Got it. Thanks for the hint. Will open an issue there and close this one.
