### ISSUE TITLE
Disable the `Warning: Manifest directory path was explicitly defined`

### ISSUE THREAD

**Issue by jozefizso** [microsoft/sbom-tool#500]
We use the `sbom-tool` to generate SBOM for our .NET project output.

This is the command line call:

```pwsh
sbom-tool generate -b "${{ github.workspace }}/dist" `
    -bc "${{ github.workspace }}/src" `
    -pn "Acme Product Name" `
    -pv "${{ steps.build.outputs.app_full_version }}" `
    -ps "Acme Company" `
    -m "${{ github.workspace }}"
```

It will emit this warning:

```
Warning: Manifest directory path was explicitly defined. Will not attempt to delete any existing _manifest directory.
```

As we have zero warnings policy in the GitHub Actions build pipeline, this will fail our builds.

And the message is not event actionable. We are basically using the tool with normal set of parameters.

**Comment by DaveTryon** [comment]
Fix has been merged and will be included in our next release
