### ISSUE TITLE
Improve component detection error handling

### ISSUE THREAD

**Issue by sfoslund** [microsoft/sbom-tool#505]
We have been seeing support requests in which the component detection library throws errors in a scan, usually due to malformed packages present on the machine, and the SBOM tool surfaces those errors before continuing the scan. This can be confusing to users, who see these errors (which are displayed in red, along with a full stack trace) and think that the SBOM generation failed. Further, this can obscure other, more critical errors. 

We should wrap component detection errors such that they are only displayed as warnings when they are not critical and the scan can continue.

**Comment by DaveTryon** [comment]
Component detection logs directly, so doing this will require either that we change component detection or find a way to replace the default implementation of `Serilog.ILogger` with our own version.

**Comment by DaveTryon** [comment]
This has been merged into main and will be included in our next release
