### ISSUE TITLE
Improve error when BuildDropPath is a file

### ISSUE THREAD

**Issue by jalkire** [microsoft/sbom-tool#522]
Currently, if BuildDropPath is set to a file, the tool's output ends with something like:
```
BuildDropPath directory not found for 'D:\a\_work\1\a\File.zip'
```
While this is accurate, users often do not realize that the issue is that a _directory_ was not found and instead think the tool could not find their file. We should update the error to make the solution more apparent.

**Comment by DaveTryon** [comment]
Fix has been merged and will be included in our next release
