### ISSUE TITLE
SBOM package detector warning.

### ISSUE THREAD

**Issue by zongtaol** [microsoft/sbom-tool#528]
I got two question about warning note while running msft-sbom-tool 2.2.2 version.

1. Does msft-sbom tool support C/C++ based project in component detection?

We noticed SBOM Generation isn't capturing any packages and throws the below mentioned warning. Does C/C++ projected supported? if not, will this been enabled in the future?
##[warning]There were no packages detected during the generation workflow.
![No_packages](https://github.com/microsoft/sbom-tool/assets/91494184/b21a2b1c-291e-41d7-9354-76fa49fccf06)

2.  We noticed few of the component has been skipped. For example tensorflow and keras. Is this expected behavior or something need to be change on python requirement.txt.

]Candidate version ("protobuf 5.26.0 - pip") for "protobuf" already exists in map and the version is NOT valid.
##[warning]Specifiers: "!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3" for package "tensorflow-cpu-aws" caused this.
##[warning]Candidate version ("tensorboard 2.15.2 - pip") for "tensorboard" already exists in map and the version is NOT valid.
##[warning]Specifiers: "<2.17,>=2.16" for package "tensorflow" caused this.
##[warning]Version Resolution for "tensorboard" failed, assuming last valid version is used.
##[warning]Candidate version ("keras 2.15.0 - pip") for "keras" already exists in map and the version is NOT valid.
##[warning]Specifiers: ">=3.0.0" for package "tensorflow" caused this.

##[warning]Components skipped for "Pip" detector:
##[warning]- "abi-pytestfixture-integration"
##[warning]- "abi-core"
##[warning]- "abi-package"
##[warning]- "abi-vault"
##[warning]- "numpy=1.26.4"

![tensorflow](https://github.com/microsoft/sbom-tool/assets/91494184/91bc9c8a-f7ca-4480-ac92-6f42ba9d44bc)

And I specify PIP_EXTRA_INDEX_URL as an internal link in system environment as well as in requirement.txt, but all the package is still not found in component detection. Do you know who can we resolve this warning message?

##[warning]Received NotFound "Not Found" from https://pypi.org/pypi/abi-core/json
##[warning]Root dependency "abi-core" not found on pypi. Skipping package.
##[warning]Received NotFound "Not Found" from https://pypi.org/pypi/abi-package/json
##[warning]Root dependency "abi-package" not found on pypi. Skipping package.
##[warning]Received NotFound "Not Found" from https://pypi.org/pypi/abi-vault/json
##[warning]Root dependency "abi-vault" not found on pypi. Skipping package.

Thank you.

**Comment by sfoslund** [comment]
Hi @zongtaol, all of your questions appear to be related to component detection, a library that the sbom-tool leverages but which does not live in this repo. If that's the case, please file an issue in the [component detection repo](https://github.com/microsoft/component-detection) instead and they will be able to assist you further. If you have any SBOM specific questions feel free to clarify and reopen this issue. Thanks!
