### ISSUE TITLE
Bug in `-mi` option and invalid SBOMConfig

### ISSUE THREAD

**Issue by sfoslund** [microsoft/sbom-tool#530]
Filed on behalf of @chloduan- thanks for debugging this!

The following exception when  -mi WdacCatalogManifest:1.0.0 is passed as an argument, and the CatalogManifestConfigHandler deemed the SbomConfig false/null: 
```
Encountered an error while generating hash for file D:/sbom-drops\reproBin\_manifest\wdaccatalogmanifest\WdacCatalog.cat: Failed to generate hashes for 'D:/sbom-drops\reproBin\_manifest\wdaccatalogmanifest\WdacCatalog.cat'
```
It seems that SbomConfigProvider.ConfigDictionary is dependent on individual configHandlers returning whether an SbomConfig is necessary  (false, and null if not necessary) via TryGetManifestConfig(). However,  FileHasher.GenerateHash() called by fileArrayGenerator.GenerateAsync() disregards whether a Handler's SbomConfig is null when determining if it passed/failed: [see code](https://github.com/microsoft/sbom-tool/blob/4915b726f8603aad5153b1eba91b48208defb87e/src/Microsoft.Sbom.Api/Executors/FileHasher.cs#L122) 

When -mi is not empty, and ManifestInfo handlers returns null/false for TryGetManifestConfig(), FileHasher's condition would return false, throwing the exception. When in fact, it filehashes == null because there was no valid SbomConfig (ConfigsDictionary.Count = 0) to hash in the first place, not because it failed to generate the hash. The bug only occurs when no other non-null manifestInfos in the list. Ex. If  -mi SPDX1:1,WdacCatalogManifest1:1, ConfigDictionary.Count = 1, and fileHahes would not be null. 

So far there hasn't been a case where only one invalid -mi has been passed in. However, a change in the arguments can break the ManifestGeneratorTool which breaks the build.

**Comment by jalkire** [comment]
Thank you for investigating this, Chloe! We aren't going to address anything at the moment, but the info will be useful if this impacts customers in the future.
