### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sascha-andres** [microsoft/sbom-tool#54]
When trying to run salus on a go project and after `Scan Manifest file` I get the mentioned error. I tried with one of my own and another open source project, both fail.

I attach the scan files for you, just in case you need them to give me a hint

Thanks for looking into this

[ScanManifest_20220714111446.txt](https://github.com/microsoft/sbom-tool/files/9110450/ScanManifest_20220714111446.txt)
[ScanManifest_20220714110630.txt](https://github.com/microsoft/sbom-tool/files/9110452/ScanManifest_20220714110630.txt)
.

**Comment by aasim** [comment]
Sorry this was a known issue due to us trimming the binaries to save space. Please try out the new version 0.1.3 of the tool, that has the fix for this issue.
https://github.com/microsoft/sbom-tool/releases/tag/v0.1.3
