### ISSUE TITLE
sbom-tools dosn't run on kali linux

### ISSUE THREAD

**Issue by aminnaseri** [microsoft/sbom-tool#560]
I run sbom-tools on same project folder in windows and kali and it worked on windows perfectly but in kali can't create sbom.
Dependencies are in .csproj file and i think this is happend because kali consider .csproj filles as plain text file.
How should i fix this problem?

**Comment by jalkire** [comment]
Thank you for reporting this behavior! Could you share more information describing the steps you are taking and the error message that you are encountering? Also, what architecture is your kali linux environment (x86, x64, ARM64)?

**Comment by DaveTryon** [comment]
Hi, @aminnaseri! We're still waiting to hear back from you on this. We'll need to close this out as non-actionable unless we hear from you soon. Thanks!
