### ISSUE TITLE
sbom always no packages detected

### ISSUE THREAD

**Issue by calvin3192** [microsoft/sbom-tool#586]
>sbom generate -b "./blaze-sbom" -bc "./blaze-2.1.2" -pn "blaze" -pv "v1" -ps "nice" -D "true"
I have put some exe or dll file in /blaze-2.1.2
but always show no packages detected ........

**Comment by sfoslund** [comment]
Hi @calvin3192, If you only have exe and dll files in your `BuildComponentsPath` then it is expected that no packages would be detected. Package detection is performed by component detection, which uses any package metadata files found in the `BuildComponentPath` directory to determine what packages are present. If you do not have any of these metadata files, it will not be able to detect any packages. See the [component detection docs for more details about which metadata files component detection looks for](https://github.com/microsoft/component-detection/blob/main/docs/feature-overview.md).

**Comment by sfoslund** [comment]
Feel free to reopen if you have further questions, thanks!
