### ISSUE TITLE
Salus name conflicts with existing tool

### ISSUE THREAD

**Issue by stevespringett** [microsoft/sbom-tool#59]
The name "Salus" is already an established security tool, which among other things generates CycloneDX SBOMs from dependency manifests. Salus is a project from Coinbase, and has been listed on the [CycloneDX Tool Center](https://cyclonedx.org/tool-center/) for quite some time now.

https://github.com/coinbase/salus

Microsoft Salus creates confusion in the market and should be renamed.

**Comment by johnterickson** [comment]
Thanks for pointing this out @stevespringett. Addressed in #65.  Blog post is being updated as well.
