### ISSUE TITLE
Question: For offline installation, are the manifest.json files no longer required?

### ISSUE THREAD

**Issue by richardzaat** [microsoft/sbom-tool#605]
Hi,

In v2.2.4 the release holds *-manifest.spdx.json files for each platform. Since v2.2.5 they are not deployed as part of a release. Are they no longer required as part of the release itself?

KR, Richard

**Comment by DaveTryon** [comment]
Adding some more detail here, the asset files in [v2.2.4](https://github.com/microsoft/sbom-tool/releases/tag/v2.2.4) included the SBOM's for the SBOM tool. The asset files in [v2.2.5](https://github.com/microsoft/sbom-tool/releases/tag/v2.2.5) and [v2.2.6](https://github.com/microsoft/sbom-tool/releases/tag/v2.2.6) do not. Specifically, the following files did not get included in the release:

- linux-x64-manifest.spdx.json
- osx-x64-manifest.spdx.json
- win-x64-manifest.spdx.json

**Comment by DaveTryon** [comment]
@richardzaat, this was unintentional. The layout of our build pipeline changed, and the release pipeline didn't reflect that change. I've manually added the files to releases 2.2.5 and 2.2.6, and have a task to bring the release pipeline back into sync. Hopefully we'll have it in place by the time we release 2.2.7.

**Comment by sfoslund** [comment]
We have updated our release pipeline to automatically include manifest files in the release assets, so this should not be an issue going forward.
