### ISSUE TITLE
2.2.7 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [microsoft/sbom-tool#626]
👋 looks like 2.2.7 release was tagged, but the release notes did not get created. Raise this issue for awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/178909 

cc @DaveTryon

**Comment by DaveTryon** [comment]
@chenrui333, we'll be completing this today.

**Comment by chenrui333** [comment]
Thanks @DaveTryon! 🙏

**Comment by DaveTryon** [comment]
@chenrui333, release is complete. Closing this issue.
