### ISSUE TITLE
Generated SBOM includes Git data and ephemeral build artifacts

### ISSUE THREAD

**Issue by waynebeaton** [microsoft/sbom-tool#63]
The generated SBOM includes information from the `.git` folder. Likewise, it would be good to have it ignore the contents of NPM `node_modules` directories and Maven `/target/` directories. 

AFAICT, there's no option to exclude these directories from the results.

One option would be to have the tool honour the ignore list specified in `.gitignore` files.

Note that a `.gitignore` file itself is a maintained artifact that IMHO should be included in the SBOM.

**Comment by tarun06** [comment]
@aasim May i asked if this gets prioritized and is going to be available soon? If not, Could you please share your thoughts on how  it should be implemented in SBOM?

I see component detector uses minimatch to filter specific directories. Do SBOM also expected similar to that solution?

**Comment by rinshadka** [comment]
Hi, any update on this. Thanks

**Comment by jlperkins** [comment]
One could use this argument: https://github.com/microsoft/sbom-tool/blob/main/docs/sbom-tool-cli-reference.md#excluding-directories-from-component-scan
Though this may have issues (based on #494)
