### ISSUE TITLE
Does not detect Maven pom.xml file

### ISSUE THREAD

**Issue by waynebeaton** [microsoft/sbom-tool#64]
I've only just started tinkering with the tool, so I may be missing something important.

The tool fails to find a `pom.xml` file in the directory that I specify as the `BuildComponentPath`, nor any of the other `pom.xml` files in nested directories. It does find two `package-lock.json` and one `yarn.lock` file nested in the build component path hierarchy.

Is some additional configuration required for Maven support? Am I missing something important?

**Comment by ByAgenT** [comment]
@waynebeaton do you have Maven installed and available in your PATH? IIRC it should be installed to detect Maven components. You can also try to run the tool with `-Verbosity Verbose`, it may give you move information about why some component detection doesn't work.

**Comment by aasim** [comment]
@waynebeaton as Anton mentioned, you need to have `mvn` in your path for detection to work. You can read more about how we detect maven packages [here](https://github.com/microsoft/component-detection/blob/1be0a786d9b543631b43c42df3b4637545cbeed3/docs/detectors/maven.md#L2).

**Comment by waynebeaton** [comment]
That did it. Thanks.
