### ISSUE TITLE
Win64 release installer ends with no output and no 'generate' becomes available.

### ISSUE THREAD

**Issue by nuvan** [microsoft/sbom-tool#67]
I'm using a Windows 11 machine. I've downloaded the installer executable from the Releases section and run it after going over the security dialogue.
The console applications close almost instantly and I can't find any 'generate' command.

**Comment by aasim** [comment]
How are you running the command? The binary in the releases page is not an installer, but a CLI executable. You need to open a new powershell or cmd window and run the command inside there to generate the SBOM.
