### ISSUE TITLE
Build fails on VS2022 due to IDE0044 and similar errors

### ISSUE THREAD

**Issue by LucaBlackDragon** [microsoft/sbom-tool#687]
I am trying to make a PR for #584 but the build fails on Visual Studio 2022 (17.11.1).
It looks like it is ignoring the `.editorconfig` rules, e.g.:

https://github.com/microsoft/sbom-tool/blob/5e1b579181048c1401b6c7e30aca94daaee8c502/.editorconfig#L1007

> 1>Build FAILED.
> 1>
> 1>C:\Users\redacted\Dev\sbom-tool\src\Microsoft.Sbom.Contracts\Contracts\Enums\AlgorithmName.cs(22,34,22,45): error IDE0044: Make field readonly (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044)
> 1>C:\Users\redacted\Dev\sbom-tool\src\Microsoft.Sbom.Contracts\Contracts\Enums\AlgorithmName.cs(22,34,22,45): error IDE0044: Make field readonly (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0044)
> 1>    0 Warning(s)
> 1>    2 Error(s)

[This](https://github.com/user-attachments/files/16726345/build-errors.txt) is the full build output.

I'm on a Windows 11 PC with .NET 8 SDK, everything is updated to the latest available stable release (and I've deactivated the SonarLint extension which caused further errors).

I can work around these issues by adding a suppression file or `#pragma` comments, but I don't think this would be correct, am I right?

**Comment by DaveTryon** [comment]
@LucaBlackDragon, I can't repro this. Here are the steps I did:

- Updated to VS 2022 17.11.1
- Ran `git clean -fdx` from the project root
- Opened the solution in VS
- Build > Rebuild Solution
- Exited VS
- Ran `git clean -fdx` from the project root
- Ran `dotnet build` from the project root

Everything worked as expected. I explicitly changed line 1007 of the .editorconfig file from 
```
dotnet_diagnostic.IDE0044.severity = suggestion
```
to
```
dotnet_diagnostic.IDE0044.severity = error
```

and then I got the failure that you're seeing. The warning behavior seems to be local to your config, although I honestly have no idea what would cause that. Please don't add any pragmas to the code to address this. Making IDE0044 error permanently would touch about 6 files and only take a few minutes to create. If you wanted to open a PR to that effect, that would be a far better option than dropping in pragmas that are not needed on other systems.

I'll ask a couple of my colleagues to try to build with the latest VS release. We'll close it out if we can't repro.

**Comment by LucaBlackDragon** [comment]
I'm closing this as the problem looks to be due to Visual Studio issues with `editorconfig` files in general.

Today I made some more research and I've found *a ton* of comments and issues like [this](https://github.com/dotnet/roslyn/issues/60377#issuecomment-2181566715):
> I had a similar issue in my team, my VS highlight errors and add suggestions from .editorconfig rules but my other team members open the same project on their VS versions and their VS doesn't respect/load .editorconfig rules at all.

**Comment by LucaBlackDragon** [comment]
SMALL UPDATE:
- checked out the project on a different PC (Win 11, VS2022, .NET 8 again): same build errors
- launched a Codespace here on Github (default image) and ran `dotnet build`: build succeeded
