### ISSUE TITLE
Question: When using Self-provided data-based SBOM generator API, how does one introduce relationships?

### ISSUE THREAD

**Issue by vichor** [microsoft/sbom-tool#688]
Sorry if this is not the way to get support, but I saw another post sending a question and I don't know where to discuss this other than here. I will gladly accept a location to do so, if this is not the proper place.

My question:
I’m using the Self-provided data-based SBOM generator API to create SBOMs for embedded software products in a specific industry. It’s common to use third-party products in this industry, so these third parties must appear in the SBOM.

I am creating SbomFile, SbomPackage, and SBOMRelationship objects and then using generator.GenerateSbomAsync. However, this method only accepts a list of files and packages as input, not a list of relationships.

How can I ensure the generator takes the relationships into account?

**Comment by DaveTryon** [comment]
Hi, @vichor!

  This functionality does not exist, making this a feature request. Our team is currently prioritizing other work and will not be able to add this anytime in the near future. I'm closing this out as not planned.
