### ISSUE TITLE
Release 2.2.7 and 2.2.8 SBOM files missing or incorrect file extension.

### ISSUE THREAD

**Issue by canon-cmi-brian-mcdonald** [microsoft/sbom-tool#707]
Release 2.2.7 has an extra ".json" extentsion for the related sbom files (https://github.com/microsoft/sbom-tool/releases/tag/v2.2.7)

- File linux-x64-manifest.spdx.json.json should be linux-x64-manifest.spdx.json
- File osx-x64-manifest.spdx.json.json should be osx-x64-manifest.spdx.json
- File win-x64-manifest.spdx.json.json should be win-x64-manifest.spdx.json

Release 2.2.8 is missing all SBOM files listed above (https://github.com/microsoft/sbom-tool/releases/tag/v2.2.8)

**Comment by sfoslund** [comment]
Thanks for the heads up! I have fixed this issue in our previous releases and we will make sure this doesn't happen again in the future, thanks!
