### ISSUE TITLE
distribute the binaries as dotnet tool install sbom-tool

### ISSUE THREAD

**Issue by rgl** [microsoft/sbom-tool#73]
it would be pretty convenient to be able to install the binaries with `dotnet tool install sbom-tool` and run it as `dotnet tool run sbom-tool`.

this would let us declare all the project tool dependencies in the `.config/dotnet-tool.json` file and restore them all with `dotnet tool restore`.

**Comment by blowdart** [comment]
It would also be an improvement over the OS specific install instructions, it would be pulling in signed nuget packages, and would work with any pipeline that can install .NET
