### ISSUE TITLE
sbom-tool generate -ManifestDirPath _manifest creates nested directory

### ISSUE THREAD

**Issue by rgl** [microsoft/sbom-tool#74]
Executing `sbom-tool generate -ManifestDirPath _manifest` creates an unexpected `_manifest` nested sub-directory:

![image](https://user-images.githubusercontent.com/43356/180485325-c0ecd13e-cff8-43ad-997d-5df11c3c9ef3.png)

Just to clarify, although this is written in the documentation, I think its not the expected behaviour:

```
ManifestDirPath (-m)                      The path of the directory where the generated SBOM files will be
                                          placed. A folder named '_manifest' will be created at this location,       
                                          where all generated SBOMs will be placed. If this parameter is not
                                          specified, the files will be placed in {BuildDropPath}/_manifest
                                          directory.
```

If this is working as expected (I hope not, because creating an hardcoded directory is really odd when you can specify it in an argument), I think the last paragraph should be modified to be a bit more clear. Something like:

> If this parameter is not specified, the directory will be create inside the {BuildDropPath} directory.

**Comment by aasim** [comment]
We create the _manifest directory automatically. You don't have to specify the `_manifest` directory yourself. You can just specify the directory where you want the SBOM to be stored in that parameter, so in this case the `net6.0` directory.

**Comment by rgl** [comment]
I was just trying to say that from a first-user perspective, the creation of the `_manifest` directory is somewhat unexpected (actually, the creation of any directory is unexpected to me). Because the argument name kinda leads one to assume that the value we set will be the final directory, and the manifest would be placed immediately there; but instead, we find the actual manifests in a two-level depth directory.

**Comment by MiYanni** [comment]
@aasim This is the exact same issue I mentioned from here in that email thread: https://github.com/microsoft/dropvalidator/issues/498

I'm telling ya, the description of that parameter is extremely misleading. It really shouldn't be generating a `_manifest` directory, and wasn't doing this prior to the changes in June. I 100% agree with @rgl here that the documentation needs updated if this is intended.

**Comment by edgarrs** [comment]
@aasim , should we just update the documentation?
