### ISSUE TITLE
ScanLinuxAsync logged InvalidOperationException: cannot hijack chunked or content length stream

### ISSUE THREAD

**Issue by newertp** [microsoft/sbom-tool#77]
[INFO] ScanLinuxAsync logged InvalidOperationException: cannot hijack chunked or content length stream
[WARN] Scanning of image sha256:xxxxxxxxxxxxx failed with exception: cannot hijack chunked or content length stream

I encountered the problem above when I scan docker images. How to fix this?

**Comment by edgarrs** [comment]
@newertp, Can you provide more details about the repro so we can help out?

**Comment by newertp** [comment]
[INFO] Finding components... 
[VERBOSE] shrinkwrap.yaml:pnpm-lock.yaml 
[VERBOSE] Cargo.lock 
[VERBOSE] yarn.lock 
[VERBOSE] Gemfile.lock 
[VERBOSE] Cargo.lock 
[VERBOSE] *.spdx.json 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Pnpm.PnpmComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Spdx.Spdx22ComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Rust.RustCrateV2Detector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Ruby.RubyComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Yarn.YarnLockComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Rust.RustCrateDetector 
[VERBOSE] package.json 
[VERBOSE] *.nupkg:*.nuspec:nuget.config 
[VERBOSE] setup.py:requirements.txt 
[VERBOSE] Podfile.lock 
[VERBOSE] project.assets.json 
[INFO] Starting enumeration of /xxx/xxx
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.NuGet.NuGetComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Pip.PipComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.NuGet.NuGetProjectModelProjectCentricComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.CocoaPods.PodComponentDetector 
[VERBOSE] go.mod:go.sum 
[VERBOSE] pom.xml 
[VERBOSE] package-lock.json:npm-shrinkwrap.json:lerna.json 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Go.GoComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Maven.MvnCliComponentDetector 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Npm.NpmComponentDetectorWithRoots 
[VERBOSE] *.lockfile 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Gradle.GradleComponentDetector 
[VERBOSE] ivy.xml 
[VERBOSE] Registered Microsoft.ComponentDetection.Detectors.Ivy.IvyDetector 
[VERBOSE] Skipping maven detection as maven is not available in the local PATH. 
[VERBOSE] Skipping Ivy detection as ant is not available in the local PATH.
[INFO] Enumerated 153 files and 28 directories in 00:00:00.1567020 
[INFO] Getting Python data from https://pypi.org/pypi/amqp/json 
[INFO] Base image annotations not found on image sha256: xxxxxx, Results will not be mapped to base image layers 
.... 
[INFO] ScanLinuxAsync logged InvalidOperationException: cannot hijack chunked or content length stream
[WARN] Root dependency celery[sqs] not found on pypi. Skipping package. 
[INFO] Getting Python data from https://pypi.org/pypi/certifi/json 
[WARN] Scanning of image sha256:xxxxxx failed with exception: cannot hijack chunked or content length stream 

The command is as follows:
salus Generate -b ./test -bc ./test -di test:latest -pn Test -pv 0.0.1 -nsb https://test.com -V Verbose -m .

**Comment by aasim** [comment]
Is this a x86 or a ARM container? Currently only x86 containers are supported

**Comment by newertp** [comment]
I have changed the container platform to x86, but still encountered the error.
