### ISSUE TITLE
"No Packages Detected" for Java Maven Project

### ISSUE THREAD

**Issue by zean0301** [microsoft/sbom-tool#796]
I am encountering an issue when generating an SBOM (Software Bill of Materials) for my Java Maven project. The tool outputs the warning: ##[warning]There were no packages detected during the generation workflow, and I’m unsure why this is happening.

Here is the setup:
- **Project Path**: `C:\AppServ\www\api_3.0`
- **Project Structure**:
```
api_3.0
├─.idea
├─.mvn
├─conf
├─key
├─log
├─src
├─upload
├─userfiles
├─usertemplates
├─mvnw
├─mvnw.cmd
├─pom.xml
└─vendor
```

- **Command Used**:
```shell
sbom generate -b "C:\Users\user\Desktop\sbom" -bc "C:\AppServ\www\api_3.0" -pn "api3.0" -pv "v1" -ps "nics" -D "true"
```
Despite having pom.xml in the project root, the tool doesn’t detect any packages. I would appreciate any guidance or suggestions on resolving this issue.

**Comment by jalkire** [comment]
Hi @zean0301, thank you for reporting this behavior! We get packages from [component-detection](https://github.com/microsoft/component-detection)--you can configure additional parameters to pass to it using our `AdditionalComponentDetectorArgs (-cd)` arg. If you're able to get CD to find your packages but not sbom-tool, please let us know.
