### ISSUE TITLE
[Microsoft.Sbom.Targets] Use fully qualified MSBuild task name for Unzip task in targets file

### ISSUE THREAD

**Issue by bstadick** [microsoft/sbom-tool#801]
The Unzip task used in [Microsoft.Sbom.Targets.targets:50](https://github.com/microsoft/sbom-tool/blob/4c2fc7780f6d866ddf4575dbeb1ac4f4db1ffc8e/src/Microsoft.Sbom.Targets/Microsoft.Sbom.Targets.targets#L50) can conflict with other tasks  also named Unzip from other MSBuild task packages such as MSBuildCommunityTasks. To avoid such conflicts it would be best to use the fully qualified task name `Microsoft.Build.Tasks.Unzip` for the Unzip task.

Suggestion:
`<Microsoft.Build.Tasks.Unzip DestinationFolder="$(NugetPackageUnzip)" SourceFiles="$(NugetPackage)" OverwriteReadOnlyFiles="true" ContinueOnError="ErrorAndContinue" />`

**Comment by sfoslund** [comment]
Fixed in https://github.com/microsoft/sbom-tool/pull/803
