### ISSUE TITLE
SBOM for C/C++ (Cmake)

### ISSUE THREAD

**Issue by sgupta22altair** [microsoft/sbom-tool#81]
sbom-tool is able to generate sbom for C/C++ projects if it is using cmake

**Comment by aasim** [comment]
@sgupta22altair do you have a question?

**Comment by vasokot** [comment]
Do this tools support Cmake files ?

**Comment by g-sahil22** [comment]
I tried to generate SBOM for https://github.com/openpbs/openpbs, but didn't works
