### ISSUE TITLE
The referencecategory should be PACKAGE_MANAGER

### ISSUE THREAD

**Issue by rabauke** [microsoft/sbom-tool#821]
The `referenceCategory` should be `PACKAGE_MANAGER`, not `PACKAGE-MANAGER`. The SPDX standard version 2.2 defines 

- `OTHER`, `SECURITY` and `PACKAGE_MANAGER` 

as valid values for `referenceCategory`, see https://github.com/spdx/spdx-spec/blob/2dffb51097904e03d5e9b19782e9d1b5cd7c9682/schemas/spdx-schema.json#L273, whereas version 2.2.2 allows

- `OTHER`, `PERSISTENT-ID`, `PERSISTENT_ID`, `SECURITY`, `PACKAGE-MANAGER`, and `PACKAGE_MANAGER`

see https://github.com/spdx/spdx-spec/blob/e3a5c7bb395c7c8b4bb55e7eaf9cb42661de9872/schemas/spdx-schema.json#L320.

As sbom-tool creates version 2.2 SPDX files and for better portability, `PACKAGE_MANAGER` should be used. The use of `PACKAGE-MANAGER` leads to parsing errors when parsing SBOM files with [cyclonedx-dotnet-library](https://github.com/CycloneDX/cyclonedx-dotnet-library). Other tools might be affected as well.

This relates to issue #108. (There might be a mismatch between the written SPDX documentation and the SPDX schema.)

**Comment by jlperkins** [comment]
Based on [this issue](https://github.com/spdx/spdx-spec/issues/792) in the spdx-spec repo, it looks like this is a known discrepancy, and they now accept either format as interchangeable, even in 2.2.

If you disagree with this interpretation, please re-open this issue! Thanks much.

**Comment by rabauke** [comment]
@jlperkins Thanks for clarifying the history of the `PACKAGE_MANAGER`-vs.-`PACKAGE-MANAGER` issue. To my understanding, the bottom line of the whole story is that spdx parsers should be less rigorous and accept both variants.

**Comment by jlperkins** [comment]
Yes, that's my understanding as well. :)
