### ISSUE TITLE
Wrong supplier in RootPackage of SBOM

### ISSUE THREAD

**Issue by Brend-Smits** [microsoft/sbom-tool#84]
Hey there, 

I am working on generating an SBOM for a GitHub Action that sets up this SBOM-Tool in a convenient way (see: https://github.com/philips-software/sbom-tool-installer-action). After generating the SBOM, I noticed that the [supplier](https://spdx.github.io/spdx-spec/package-information/#75-package-supplier-field) field of the ``RootPackage`` is set to ``Organization: Microsoft``, which seems incorrect. 
There should be a parameter to control this value. 
  
I uploaded the SBOM as a Gist. Please have a look here:
https://gist.github.com/Brend-Smits/90b62120de7abc989c2768c92a2a49c8#file-sbom-tool-installer-action-sbom-L10757-L10772

**Comment by aasim** [comment]
Thanks for bringing this to our attention, will add a parameter to the tool for this.

**Comment by Brend-Smits** [comment]
> Thanks for bringing this to our attention, will add a parameter to the tool for this.

Is this something I can help with? I don't mind opening a PR.

**Comment by edgarrs** [comment]
Thanks @Brend-Smits , @ByAgenT is already working on a fix for this. But how about you help us fixing https://github.com/microsoft/sbom-tool/issues/85?
