### ISSUE TITLE
Missing license of RootPackage in SBOM

### ISSUE THREAD

**Issue by Brend-Smits** [microsoft/sbom-tool#85]
Hey there, 

I am working on generating an SBOM for a GitHub Action that sets up this SBOM-Tool in a convenient way (see: https://github.com/philips-software/sbom-tool-installer-action). After generating the SBOM, I noticed that the [license](https://spdx.github.io/spdx-spec/package-information/#713-concluded-license-field) field of the ``RootPackage`` is set to ``NOASSERTION``. This might be intended as this feature might not be implemented yet. However, I would really appreciate at least a parameter to set the LICENSE of the RootPackage. In the case of the installer-action, the license is actually set properly within GitHub and the package.json

I uploaded the SBOM as a Gist. Please have a look here:
https://gist.github.com/Brend-Smits/90b62120de7abc989c2768c92a2a49c8#file-sbom-tool-installer-action-sbom-L10757-L10772

**Comment by edgarrs** [comment]
Hi @Brend-Smits, would you like to send a PR for this?
